name: Deploy with SFTP

on: 
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: projetoscti.com.br
        username: eq3ini3b
        password: ${{ secrets.ftp_password }}
        remote_path: /api/
        local_path: ./dist/
        sftpArgs: '-o ConnectTimeout=5'